package terraform

import (
	"fmt"
	"strings"

	"github.com/kishininfosec/infra-gen/infra-gen/pkg/types"
)

// Generator implements Terraform HCL generation using only standard library
type Generator struct{}

// NewGenerator creates a new Terraform generator
func NewGenerator() *Generator {
	return &Generator{}
}

// GetTarget returns the target type
func (g *Generator) GetTarget() types.Target {
	return types.TargetTerraform
}

// Generate generates Terraform files from project config
func (g *Generator) Generate(config *types.ProjectConfig) ([]types.GeneratedFile, error) {
	if err := g.Validate(config); err != nil {
		return nil, err
	}

	files := []types.GeneratedFile{}

	// Generate main.tf
	mainContent := g.generateMainTF(config)
	files = append(files, types.GeneratedFile{
		Path:     "main.tf",
		Content:  mainContent,
		Type:     types.TargetTerraform,
		Encoding: "utf-8",
	})

	// Generate variables.tf
	varsContent := g.generateVariablesTF(config)
	files = append(files, types.GeneratedFile{
		Path:     "variables.tf",
		Content:  varsContent,
		Type:     types.TargetTerraform,
		Encoding: "utf-8",
	})

	// Generate outputs.tf
	outputsContent := g.generateOutputsTF(config)
	if outputsContent != "" {
		files = append(files, types.GeneratedFile{
			Path:     "outputs.tf",
			Content:  outputsContent,
			Type:     types.TargetTerraform,
			Encoding: "utf-8",
		})
	}

	// Generate provider.tf
	providerContent := g.generateProviderTF(config)
	files = append(files, types.GeneratedFile{
		Path:     "provider.tf",
		Content:  providerContent,
		Type:     types.TargetTerraform,
		Encoding: "utf-8",
	})

	return files, nil
}

// Validate validates the project config for Terraform generation
func (g *Generator) Validate(config *types.ProjectConfig) error {
	var errors types.ValidationErrors

	if config.Name == "" {
		errors.Add("name", "project name is required", config.Name)
	}

	if len(config.Services) == 0 {
		errors.Add("services", "at least one service is required", len(config.Services))
	}

	// Validate each service
	for i, service := range config.Services {
		if service.Name == "" {
			errors.Add(fmt.Sprintf("services[%d].name", i), "service name is required", service.Name)
		}
		if service.Type == "" {
			errors.Add(fmt.Sprintf("services[%d].type", i), "service type is required", service.Type)
		}
	}

	if errors.HasErrors() {
		return errors
	}

	return nil
}

// generateMainTF generates the main Terraform configuration
func (g *Generator) generateMainTF(config *types.ProjectConfig) string {
	var builder strings.Builder

	builder.WriteString("# Terraform configuration for ")
	builder.WriteString(config.Name)
	builder.WriteString("\n# Generated by infra-gen\n\n")

	// Generate resources for each service
	for _, service := range config.Services {
		if !service.Enabled {
			continue
		}

		switch service.Type {
		case "web", "frontend", "nginx":
			g.generateWebServer(&builder, service, config)
		case "database", "postgres", "mysql":
			g.generateDatabase(&builder, service, config)
		case "api", "backend":
			g.generateAPIServer(&builder, service, config)
		default:
			g.generateGenericService(&builder, service, config)
		}
	}

	return builder.String()
}

// generateVariablesTF generates Terraform variables
func (g *Generator) generateVariablesTF(config *types.ProjectConfig) string {
	var builder strings.Builder

	builder.WriteString("# Input variables\n")
	builder.WriteString("variable \"project_name\" {\n")
	builder.WriteString("  description = \"Name of the project\"\n")
	builder.WriteString("  type        = string\n")
	builder.WriteString("  default     = \"")
	builder.WriteString(config.Name)
	builder.WriteString("\"\n}\n\n")

	builder.WriteString("variable \"environment\" {\n")
	builder.WriteString("  description = \"Environment (dev, staging, prod)\"\n")
	builder.WriteString("  type        = string\n")
	builder.WriteString("  default     = \"")
	if config.Environment != "" {
		builder.WriteString(config.Environment)
	} else {
		builder.WriteString("dev")
	}
	builder.WriteString("\"\n}\n\n")

	// Add service-specific variables
	for _, service := range config.Services {
		if !service.Enabled {
			continue
		}

		varName := strings.ReplaceAll(service.Name, "-", "_")
		builder.WriteString("variable \"")
		builder.WriteString(varName)
		builder.WriteString("_image\" {\n")
		builder.WriteString("  description = \"Docker image for ")
		builder.WriteString(service.Name)
		builder.WriteString("\"\n")
		builder.WriteString("  type        = string\n")
		if service.Image != "" {
			builder.WriteString("  default     = \"")
			builder.WriteString(service.Image)
			builder.WriteString("\"\n")
		}
		builder.WriteString("}\n\n")
	}

	// Add project variables
	for key, value := range config.Variables {
		builder.WriteString("variable \"")
		builder.WriteString(key)
		builder.WriteString("\" {\n")
		builder.WriteString("  description = \"")
		builder.WriteString(key)
		builder.WriteString("\"\n")
		builder.WriteString("  type        = string\n")
		builder.WriteString("  default     = \"")
		builder.WriteString(value)
		builder.WriteString("\"\n")
		builder.WriteString("}\n\n")
	}

	return builder.String()
}

// generateOutputsTF generates Terraform outputs
func (g *Generator) generateOutputsTF(config *types.ProjectConfig) string {
	var builder strings.Builder

	builder.WriteString("# Output values\n")

	for _, service := range config.Services {
		if !service.Enabled {
			continue
		}

		if len(service.Ports) > 0 {
			varName := strings.ReplaceAll(service.Name, "-", "_")
			builder.WriteString("output \"")
			builder.WriteString(varName)
			builder.WriteString("_url\" {\n")
			builder.WriteString("  description = \"URL for ")
			builder.WriteString(service.Name)
			builder.WriteString("\"\n")
			builder.WriteString("  value = \"http://")
			builder.WriteString("${aws_instance.")
			builder.WriteString(varName)
			builder.WriteString(".public_ip}:")
			if len(service.Ports) > 0 {
				builder.WriteString(fmt.Sprintf("%d", service.Ports[0].Container))
			} else {
				builder.WriteString("80")
			}
			builder.WriteString("\"\n")
			builder.WriteString("}\n\n")
		}
	}

	return builder.String()
}

// generateProviderTF generates Terraform provider configuration
func (g *Generator) generateProviderTF(config *types.ProjectConfig) string {
	var builder strings.Builder

	builder.WriteString("# Terraform provider configuration\n")
	builder.WriteString("terraform {\n")
	builder.WriteString("  required_version = \">= 1.0\"\n")
	builder.WriteString("  required_providers {\n")
	builder.WriteString("    aws = {\n")
	builder.WriteString("      source  = \"hashicorp/aws\"\n")
	builder.WriteString("      version = \"~> 5.0\"\n")
	builder.WriteString("    }\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")

	builder.WriteString("# Configure AWS provider\n")
	builder.WriteString("provider \"aws\" {\n")
	builder.WriteString("  region = var.aws_region\n")
	builder.WriteString("}\n\n")

	return builder.String()
}

// Service-specific generators
func (g *Generator) generateWebServer(builder *strings.Builder, service types.ServiceConfig, config *types.ProjectConfig) {
	varName := strings.ReplaceAll(service.Name, "-", "_")

	builder.WriteString("# Web Server: ")
	builder.WriteString(service.Name)
	builder.WriteString("\n")
	builder.WriteString("resource \"aws_instance\" \"")
	builder.WriteString(varName)
	builder.WriteString("\" {\n")
	builder.WriteString("  ami           = \"ami-0c55b159cbfafe1f0\" # Amazon Linux 2\n")
	builder.WriteString("  instance_type = \"t3.micro\"\n")
	builder.WriteString("  tags = {\n")
	builder.WriteString("    Name        = \"")
	builder.WriteString(service.Name)
	builder.WriteString("\"\n")
	builder.WriteString("    Project     = var.project_name\n")
	builder.WriteString("    Environment = var.environment\n")
	builder.WriteString("  }\n\n")

	// Add security group for web server
	builder.WriteString("  vpc_security_group_ids = [aws_security_group.")
	builder.WriteString(varName)
	builder.WriteString(".id]\n")
	builder.WriteString("}\n\n")

	builder.WriteString("resource \"aws_security_group\" \"")
	builder.WriteString(varName)
	builder.WriteString("\" {\n")
	builder.WriteString("  name        = \"")
	builder.WriteString(service.Name)
	builder.WriteString("-sg\"\n")
	builder.WriteString("  description = \"Security group for ")
	builder.WriteString(service.Name)
	builder.WriteString("\"\n\n")

	// Add port rules
	for _, port := range service.Ports {
		builder.WriteString("  ingress {\n")
		builder.WriteString("    from_port   = ")
		builder.WriteString(fmt.Sprintf("%d", port.Container))
		builder.WriteString("\n")
		builder.WriteString("    to_port     = ")
		builder.WriteString(fmt.Sprintf("%d", port.Container))
		builder.WriteString("\n")
		builder.WriteString("    protocol    = \"tcp\"\n")
		builder.WriteString("    cidr_blocks = [\"0.0.0.0/0\"]\n")
		builder.WriteString("  }\n\n")
	}

	builder.WriteString("  egress {\n")
	builder.WriteString("    from_port   = 0\n")
	builder.WriteString("    to_port     = 0\n")
	builder.WriteString("    protocol    = \"-1\"\n")
	builder.WriteString("    cidr_blocks = [\"0.0.0.0/0\"]\n")
	builder.WriteString("  }\n\n")

	builder.WriteString("  tags = {\n")
	builder.WriteString("    Name        = \"")
	builder.WriteString(service.Name)
	builder.WriteString("-sg\"\n")
	builder.WriteString("    Project     = var.project_name\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")
}

func (g *Generator) generateDatabase(builder *strings.Builder, service types.ServiceConfig, config *types.ProjectConfig) {
	varName := strings.ReplaceAll(service.Name, "-", "_")

	builder.WriteString("# Database: ")
	builder.WriteString(service.Name)
	builder.WriteString("\n")
	builder.WriteString("resource \"aws_db_instance\" \"")
	builder.WriteString(varName)
	builder.WriteString("\" {\n")
	builder.WriteString("  identifier = \"")
	builder.WriteString(service.Name)
	builder.WriteString("\"\n")
	builder.WriteString("  engine     = \"postgres\"\n")
	builder.WriteString("  instance_class = \"db.t3.micro\"\n")
	builder.WriteString("  allocated_storage = 20\n")
	builder.WriteString("  engine_version = \"15.4\"\n")
	builder.WriteString("  username   = \"admin\"\n")
	builder.WriteString("  password   = var.")
	builder.WriteString(varName)
	builder.WriteString("_password\n")
	builder.WriteString("  db_name  = \"")
	builder.WriteString(service.Name)
	builder.WriteString("\"\n")
	builder.WriteString("  skip_final_snapshot = true\n")
	builder.WriteString("  tags = {\n")
	builder.WriteString("    Name        = \"")
	builder.WriteString(service.Name)
	builder.WriteString("\"\n")
	builder.WriteString("    Project     = var.project_name\n")
	builder.WriteString("    Environment = var.environment\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")
}

func (g *Generator) generateAPIServer(builder *strings.Builder, service types.ServiceConfig, config *types.ProjectConfig) {
	varName := strings.ReplaceAll(service.Name, "-", "_")

	builder.WriteString("# API Server: ")
	builder.WriteString(service.Name)
	builder.WriteString("\n")
	builder.WriteString("resource \"aws_instance\" \"")
	builder.WriteString(varName)
	builder.WriteString("\" {\n")
	builder.WriteString("  ami           = \"ami-0c55b159cbfafe1f0\"\n")
	builder.WriteString("  instance_type = \"t3.micro\"\n")
	builder.WriteString("  tags = {\n")
	builder.WriteString("    Name        = \"")
	builder.WriteString(service.Name)
	builder.WriteString("\"\n")
	builder.WriteString("    Project     = var.project_name\n")
	builder.WriteString("    Environment = var.environment\n")
	builder.WriteString("  }\n\n")

	builder.WriteString("  vpc_security_group_ids = [aws_security_group.")
	builder.WriteString(varName)
	builder.WriteString(".id]\n")
	builder.WriteString("}\n\n")

	builder.WriteString("resource \"aws_security_group\" \"")
	builder.WriteString(varName)
	builder.WriteString("\" {\n")
	builder.WriteString("  name        = \"")
	builder.WriteString(service.Name)
	builder.WriteString("-sg\"\n")
	builder.WriteString("  description = \"Security group for ")
	builder.WriteString(service.Name)
	builder.WriteString("\"\n\n")

	// Add port rules
	for _, port := range service.Ports {
		builder.WriteString("  ingress {\n")
		builder.WriteString("    from_port   = ")
		builder.WriteString(fmt.Sprintf("%d", port.Container))
		builder.WriteString("\n")
		builder.WriteString("    to_port     = ")
		builder.WriteString(fmt.Sprintf("%d", port.Container))
		builder.WriteString("\n")
		builder.WriteString("    protocol    = \"tcp\"\n")
		builder.WriteString("    cidr_blocks = [\"0.0.0.0/0\"]\n")
		builder.WriteString("  }\n\n")
	}

	builder.WriteString("  egress {\n")
	builder.WriteString("    from_port   = 0\n")
	builder.WriteString("    to_port     = 0\n")
	builder.WriteString("    protocol    = \"-1\"\n")
	builder.WriteString("    cidr_blocks = [\"0.0.0.0/0\"]\n")
	builder.WriteString("  }\n\n")

	builder.WriteString("  tags = {\n")
	builder.WriteString("    Name        = \"")
	builder.WriteString(service.Name)
	builder.WriteString("-sg\"\n")
	builder.WriteString("    Project     = var.project_name\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")
}

func (g *Generator) generateGenericService(builder *strings.Builder, service types.ServiceConfig, config *types.ProjectConfig) {
	varName := strings.ReplaceAll(service.Name, "-", "_")

	builder.WriteString("# Generic Service: ")
	builder.WriteString(service.Name)
	builder.WriteString("\n")
	builder.WriteString("resource \"aws_instance\" \"")
	builder.WriteString(varName)
	builder.WriteString("\" {\n")
	builder.WriteString("  ami           = \"ami-0c55b159cbfafe1f0\"\n")
	builder.WriteString("  instance_type = \"t3.micro\"\n")
	builder.WriteString("  tags = {\n")
	builder.WriteString("    Name        = \"")
	builder.WriteString(service.Name)
	builder.WriteString("\"\n")
	builder.WriteString("    Project     = var.project_name\n")
	builder.WriteString("    Environment = var.environment\n")
	builder.WriteString("  }\n")
	builder.WriteString("}\n\n")
}
